name: Run Pytest

on:
  push:
    paths-ignore:
      - .gitignore
      - .github/**
      - .vscode/**
      - .idea/**
      - README.md
      - version.txt
  pull_request:

jobs:
  run-pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.11"]

    steps:  
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install GitHub plugins
        run: |
          pip install pytest-github-actions-annotate-failures
      - name: Run Tests
        run: pytest

  run-pytest-verbose:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.11"]

    steps:  
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run Tests
        run: pytest --verbose -o log_cli=true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pytest-tmp
          path: |
            '**/pytest-of-*/pytest**'
            ${{ github.workspace }}/pytest.log
